version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      - redis
      - postgres

  celery:
    build: .
    container_name: celery-worker
    command: celery -A src.celery.tasks worker --loglevel=info
    env_file:
      - src/.env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: mypostgres
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: